name: "citizens-integration"
version: "1.1"
author: SuperCuber
authors: [Voigon]
main: net.miniaturepets.citizensintegration.MiniatureNPCs
api-version: "1.13"
depend: ["Citizens", "MiniaturePets"]
commands:
